baseURL = "https://www.keenanschott.com/"
languageCode = "en-us"
title = "Keenan Schott"
theme = "smol"

pygmentsCodefences = true
pygmentsStyle = "github"
pygmentsUseClasses = true

timeout = "360s"

[outputs]
  home = ["HTML", "RSS", "JSON"]

# paginate = 15

[minify]
  minifyOutput = true

[markup]
  [markup.highlight]
    style = "github"
  [markup.goldmark.renderer]
    unsafe = true

[imaging]
  quality = 90

[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^rst2html$']
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']

  [security.funcs]
    getenv = ['^HUGO_']

  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']

[params]
  author = "Keenan Schott"
  description = "I'm a Software Engineer Intern at ICR, Inc.. This is my personal website, portfolio, and blog."
  title = "Keenan Schott"
  subtitle = "Software Engineer Intern at ICR, Inc."
  dateFmt = "01/02/2006"
  logo = "profile.jpg"

  # Theme
  themeColorAutoDetectBrowserPreference = true
  themeColor = 'dark'

  # Posts shown in homepage
  mainSections = ["posts"]

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 2

  [[menu.main]]
    identifier = "portfolio"
    name = "Portfolio"
    url = "/portfolio/"
    weight = 3

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 4

  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 5

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 6

  [[menu.main]]
    identifier = "rss"
    name = "RSS"
    url = "/index.xml"
    weight = 7

# Footer
  [[menu.footer]]
    name = "GitHub"
    url = "https://github.com/keenanschott"
    weight = 1

  [[menu.footer]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/keenanschott"
    weight = 2

[related]
  includeNewer = true
  toLower = true
  [[related.indices]]
    name = 'keywords'
    type = 'basic'
    weight = 100
  [[related.indices]]
    name = 'tags'
    type = 'basic'
    weight = 60
  [[related.indices]]
    name = 'categories'
    type = 'basic'
    weight = 30
  [[related.indices]]
    name = 'date'
    type = 'basic'
    weight = 10